import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../shared/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex p-8 justify-center items-center h-screen">
          <div className="max-w-3xl h-full flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
